name: Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  
  Latex:
    runs-on: ubuntu-latest

    steps:

      - name: 'ðŸ§° Checkout'
        uses: actions/checkout@v3

      - uses: docker://btdi/latex
        with:
          args: ./make.sh
       
      - name: 'ðŸ“¤ Upload artifact'
        uses: actions/upload-artifact@v3
        with:
          name: TMF
          path: ./main.pdf


